/*
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.ui.tests;

import com.fun.gantt.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SMDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("com.fun.gantt.example.SMDSL");
	}

}
