/*
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.tests

import com.fun.gantt.example.sMDSL.Entry
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(SMDSLInjectorProvider)
class SMDSLParsingTest{

	@Inject
	ParseHelper<Entry> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
