/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.validation;

import com.fun.gantt.example.validation.AbstractSMDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SMDSLValidator extends AbstractSMDSLValidator {
}
