/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example;

import com.fun.gantt.example.AbstractSMDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SMDSLRuntimeModule extends AbstractSMDSLRuntimeModule {
}
