/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example;

import com.fun.gantt.example.SMDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SMDSLStandaloneSetup extends SMDSLStandaloneSetupGenerated {
  public static void doSetup() {
    SMDSLStandaloneSetup _sMDSLStandaloneSetup = new SMDSLStandaloneSetup();
    _sMDSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
