/*
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSMDSLScopeProvider extends DelegatingScopeProvider {
}
