/*
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.parser.antlr;

import com.fun.gantt.example.parser.antlr.internal.InternalSMDSLParser;
import com.fun.gantt.example.services.SMDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SMDSLParser extends AbstractAntlrParser {

	@Inject
	private SMDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSMDSLParser createParser(XtextTokenStream stream) {
		return new InternalSMDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Entry";
	}

	public SMDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SMDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
