/*
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SMDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/fun/gantt/example/parser/antlr/internal/InternalSMDSL.tokens");
	}
}
