/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.scoping;

import com.fun.gantt.example.scoping.AbstractSMDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SMDSLScopeProvider extends AbstractSMDSLScopeProvider {
}
