/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.sMDSL.impl;

import com.fun.gantt.example.sMDSL.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SMDSLFactoryImpl extends EFactoryImpl implements SMDSLFactory
{
  /**
	 * Creates the default factory implementation.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public static SMDSLFactory init()
  {
		try {
			SMDSLFactory theSMDSLFactory = (SMDSLFactory)EPackage.Registry.INSTANCE.getEFactory(SMDSLPackage.eNS_URI);
			if (theSMDSLFactory != null) {
				return theSMDSLFactory;
			}
		}
		catch (Exception exception) {
			EcorePlugin.INSTANCE.log(exception);
		}
		return new SMDSLFactoryImpl();
	}

  /**
	 * Creates an instance of the factory.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public SMDSLFactoryImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public EObject create(EClass eClass)
  {
		switch (eClass.getClassifierID()) {
			case SMDSLPackage.ENTRY: return createEntry();
			case SMDSLPackage.ACTIVITY: return createActivity();
			case SMDSLPackage.DEPENDENCY: return createDependency();
			default:
				throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
		}
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Entry createEntry()
  {
		EntryImpl entry = new EntryImpl();
		return entry;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Activity createActivity()
  {
		ActivityImpl activity = new ActivityImpl();
		return activity;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Dependency createDependency()
  {
		DependencyImpl dependency = new DependencyImpl();
		return dependency;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public SMDSLPackage getSMDSLPackage()
  {
		return (SMDSLPackage)getEPackage();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @deprecated
	 * @generated
	 */
  @Deprecated
  public static SMDSLPackage getPackage()
  {
		return SMDSLPackage.eINSTANCE;
	}

} //SMDSLFactoryImpl
