/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.ui.contentassist;

import com.fun.gantt.example.ui.contentassist.AbstractSMDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SMDSLProposalProvider extends AbstractSMDSLProposalProvider {
}
