/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.ui;

import com.fun.gantt.example.ui.AbstractSMDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SMDSLUiModule extends AbstractSMDSLUiModule {
  public SMDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
