/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.sMDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Activity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.fun.gantt.example.sMDSL.Activity#getName <em>Name</em>}</li>
 *   <li>{@link com.fun.gantt.example.sMDSL.Activity#getContents <em>Contents</em>}</li>
 * </ul>
 *
 * @see com.fun.gantt.example.sMDSL.SMDSLPackage#getActivity()
 * @model
 * @generated
 */
public interface Activity extends Entry
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see com.fun.gantt.example.sMDSL.SMDSLPackage#getActivity_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link com.fun.gantt.example.sMDSL.Activity#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Contents</b></em>' containment reference list.
	 * The list contents are of type {@link com.fun.gantt.example.sMDSL.Entry}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Contents</em>' containment reference list.
	 * @see com.fun.gantt.example.sMDSL.SMDSLPackage#getActivity_Contents()
	 * @model containment="true"
	 * @generated
	 */
  EList<Entry> getContents();

} // Activity
