/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.sMDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.fun.gantt.example.sMDSL.Dependency#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see com.fun.gantt.example.sMDSL.SMDSLPackage#getDependency()
 * @model
 * @generated
 */
public interface Dependency extends Entry
{
  /**
	 * Returns the value of the '<em><b>To</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>To</em>' reference.
	 * @see #setTo(Activity)
	 * @see com.fun.gantt.example.sMDSL.SMDSLPackage#getDependency_To()
	 * @model
	 * @generated
	 */
  Activity getTo();

  /**
	 * Sets the value of the '{@link com.fun.gantt.example.sMDSL.Dependency#getTo <em>To</em>}' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>To</em>' reference.
	 * @see #getTo()
	 * @generated
	 */
  void setTo(Activity value);

} // Dependency
