/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.sMDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.fun.gantt.example.sMDSL.SMDSLPackage#getEntry()
 * @model
 * @generated
 */
public interface Entry extends EObject
{
} // Entry
