/**
 * generated by Xtext 2.10.0
 */
package com.fun.gantt.example.sMDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.fun.gantt.example.sMDSL.SMDSLFactory
 * @model kind="package"
 * @generated
 */
public interface SMDSLPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "sMDSL";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.fun.com/gantt/example/SMDSL";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "sMDSL";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  SMDSLPackage eINSTANCE = com.fun.gantt.example.sMDSL.impl.SMDSLPackageImpl.init();

  /**
	 * The meta object id for the '{@link com.fun.gantt.example.sMDSL.impl.EntryImpl <em>Entry</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see com.fun.gantt.example.sMDSL.impl.EntryImpl
	 * @see com.fun.gantt.example.sMDSL.impl.SMDSLPackageImpl#getEntry()
	 * @generated
	 */
  int ENTRY = 0;

  /**
	 * The number of structural features of the '<em>Entry</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENTRY_FEATURE_COUNT = 0;

  /**
	 * The meta object id for the '{@link com.fun.gantt.example.sMDSL.impl.ActivityImpl <em>Activity</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see com.fun.gantt.example.sMDSL.impl.ActivityImpl
	 * @see com.fun.gantt.example.sMDSL.impl.SMDSLPackageImpl#getActivity()
	 * @generated
	 */
  int ACTIVITY = 1;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ACTIVITY__NAME = ENTRY_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Contents</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ACTIVITY__CONTENTS = ENTRY_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Activity</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ACTIVITY_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link com.fun.gantt.example.sMDSL.impl.DependencyImpl <em>Dependency</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see com.fun.gantt.example.sMDSL.impl.DependencyImpl
	 * @see com.fun.gantt.example.sMDSL.impl.SMDSLPackageImpl#getDependency()
	 * @generated
	 */
  int DEPENDENCY = 2;

  /**
	 * The feature id for the '<em><b>To</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DEPENDENCY__TO = ENTRY_FEATURE_COUNT + 0;

  /**
	 * The number of structural features of the '<em>Dependency</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DEPENDENCY_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 1;


  /**
	 * Returns the meta object for class '{@link com.fun.gantt.example.sMDSL.Entry <em>Entry</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Entry</em>'.
	 * @see com.fun.gantt.example.sMDSL.Entry
	 * @generated
	 */
  EClass getEntry();

  /**
	 * Returns the meta object for class '{@link com.fun.gantt.example.sMDSL.Activity <em>Activity</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Activity</em>'.
	 * @see com.fun.gantt.example.sMDSL.Activity
	 * @generated
	 */
  EClass getActivity();

  /**
	 * Returns the meta object for the attribute '{@link com.fun.gantt.example.sMDSL.Activity#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see com.fun.gantt.example.sMDSL.Activity#getName()
	 * @see #getActivity()
	 * @generated
	 */
  EAttribute getActivity_Name();

  /**
	 * Returns the meta object for the containment reference list '{@link com.fun.gantt.example.sMDSL.Activity#getContents <em>Contents</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Contents</em>'.
	 * @see com.fun.gantt.example.sMDSL.Activity#getContents()
	 * @see #getActivity()
	 * @generated
	 */
  EReference getActivity_Contents();

  /**
	 * Returns the meta object for class '{@link com.fun.gantt.example.sMDSL.Dependency <em>Dependency</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Dependency</em>'.
	 * @see com.fun.gantt.example.sMDSL.Dependency
	 * @generated
	 */
  EClass getDependency();

  /**
	 * Returns the meta object for the reference '{@link com.fun.gantt.example.sMDSL.Dependency#getTo <em>To</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>To</em>'.
	 * @see com.fun.gantt.example.sMDSL.Dependency#getTo()
	 * @see #getDependency()
	 * @generated
	 */
  EReference getDependency_To();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  SMDSLFactory getSMDSLFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link com.fun.gantt.example.sMDSL.impl.EntryImpl <em>Entry</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see com.fun.gantt.example.sMDSL.impl.EntryImpl
		 * @see com.fun.gantt.example.sMDSL.impl.SMDSLPackageImpl#getEntry()
		 * @generated
		 */
    EClass ENTRY = eINSTANCE.getEntry();

    /**
		 * The meta object literal for the '{@link com.fun.gantt.example.sMDSL.impl.ActivityImpl <em>Activity</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see com.fun.gantt.example.sMDSL.impl.ActivityImpl
		 * @see com.fun.gantt.example.sMDSL.impl.SMDSLPackageImpl#getActivity()
		 * @generated
		 */
    EClass ACTIVITY = eINSTANCE.getActivity();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ACTIVITY__NAME = eINSTANCE.getActivity_Name();

    /**
		 * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ACTIVITY__CONTENTS = eINSTANCE.getActivity_Contents();

    /**
		 * The meta object literal for the '{@link com.fun.gantt.example.sMDSL.impl.DependencyImpl <em>Dependency</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see com.fun.gantt.example.sMDSL.impl.DependencyImpl
		 * @see com.fun.gantt.example.sMDSL.impl.SMDSLPackageImpl#getDependency()
		 * @generated
		 */
    EClass DEPENDENCY = eINSTANCE.getDependency();

    /**
		 * The meta object literal for the '<em><b>To</b></em>' reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference DEPENDENCY__TO = eINSTANCE.getDependency_To();

  }

} //SMDSLPackage
